server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelService
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085


  #  ------------TO CHANGE PROFILE
  #  profiles:
  #    active: prod

  # -----------EUREKA CONFIG IS NOW GETTING FROM spring.config.import
  #eureka:
  #  instance:
  #    prefer-ip-address: true
  #  client:
  #    fetch-registry: true
  #    register-with-eureka: true
  #    service-url:
  #      defaultZone : http://localhost:8761/eureka


